accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "MPL-2.0",
    "ISC",
    "CC0-1.0",
    "Zlib",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "Unicode-DFS-2016",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
