[workspace]

[package]
name = "STO_CombatLogAnalyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.20.1" }
chrono = "0.4.23"
lazy_static = "1.4.0"
regex = "1.7.0"
bitflags = "1.3.2"
log = "0.4.17"
rustc-hash = "1.1.0"
rfd = "0.10.0"
egui_extras = "0.20.0"
serde_json = "1.0.89"
serde = "1.0.150"
smallvec = "1.10.0"
crossbeam-channel = "0.5.6"
simplelog = "0.12.0"
notify = "5.0.0"
timer = "0.2.0"
itertools = "0.10.5"

[profile.release]
lto = "thin"
